### PR TITLE
win32 placeholder

### PR DESCRIPTION
**Pull request by illishar**
Regards from PCH Engineering A/S.
Mostly just a pull request to test out workflow and communications. The added files are a bare minimum for making the cmake project compile in Microsoft Visual Studio. Placeholder has been prepared for winsock usage. (Needed for htons etc.) Future raw ethernet usage will be performed by winpcap.

### CODE REVIEW

**Comment by pyhys** [comment]
Great, welcome!
We will have a check. Please also see https://github.com/rtlabs-com/osal/tree/master/src/windows

**Comment by pyhys** [comment]
Very nice with Windows support!
Would it be possible to use cmake to download the network library from some external location at build time? Due to the license terms the npcap files can not be included in our repository. Please see https://github.com/nmap/npcap/blob/master/LICENSE

It would be great if you look into the licensing a bit. Alternatively we could use another library, for example the older winpcap.
What do you think?
/Jonas

**Comment by illishar** [comment]
According to the license included in the Npcap SDK they're licensed the same as their original winpcap counterparts. Meaning they're copyrighted by the University of California and NetGroup. They could be downloaded from winpcap instead ofc, but they'd be the same? (Eg. this is not redistribution of Npcap. Users will have to download npcap themselves and thereby make sure that they fullfil the Npcap license.) ... should I download them from winpcap instead?

**Comment by illishar** [comment]
SDK license from Npcap and Winpcap:

 * Copyright (c) 1993, 1994, 1995, 1996, 1997
 *	The Regents of the University of California.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. All advertising materials mentioning features or use of this software
 *    must display the following acknowledgement:
 *	This product includes software developed by the Computer Systems
 *	Engineering Group at Lawrence Berkeley Laboratory.
 * 4. Neither the name of the University nor of the Laboratory may be used
 *    to endorse or promote products derived from this software without
 *    specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*
 * Remote packet capture mechanisms and extensions from WinPcap:
 *
 * Copyright (c) 2002 - 2003
 * NetGroup, Politecnico di Torino (Italy)
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the Politecnico di Torino nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

**Comment by pyhys** [comment]
Hi, and thanks for your answer. Please see the license in src/ports/windows/pcap/Include/Packet32.h
It would be great if third-party libraries are downloaded by cmake at buildtime. That would it much easier to keep it up to date, and to have a clean separation (with regards to licensing etc).

Is that possible?
/Jonas

**Comment by illishar** [comment]
So there *is* a small difference between winpcap and npcap SDK. Fair enough. I have not much idea if cmake can download and unpack the SDK. I've just spent 4 hours convicing it to make Release build. And I've given up, on making an /MT build.

**Comment by pyhys** [comment]
Hi, grear!
Please put in our standard-header in non-thirdparty files. It should have the line "Copyright 2021 rt-labs AB, Sweden."
/Jonas

**Pull request closed without merging**
