### PR TITLE
Update rt-kernel patch file

### PR DESCRIPTION
**Pull request by fredrikdanielmoller**
* Fix a defect in SNMP where wrong interface
  name (ifDescr) would be returned.
* Change IP address to 192.168.0.50 as to align
  with documentation.
* Put all RAM in a single memory section as to
  allow for a larger heap. This enables the full
  unit test program to run.
* Increase stack size for the Ethernet receive
  task as to avoid overflow when running
  ART Tester.

### CODE REVIEW

**Review by pyhys — APPROVED** [review]
Great!

**Comment by fredrikdanielmoller** [comment]
I would like to put this PR on hold for the moment. I'm seeing some issues while debugging which might be related to changes in the patch.

**Comment by fredrikdanielmoller** [comment]
Problem fixed. Sadly, running the unit-tests on rt-kernel no longer works without disabling test cases as the heap is now smaller.

**Comment by pyhys** [comment]
Great!

**Comment by hefloryd** [comment]
> Problem fixed. Sadly, running the unit-tests on rt-kernel no longer works without disabling test cases as the heap is now smaller.

It doesn't run on the xmc48relax board as it doesn't have enough memory for googletest and all test cases. It should be possible to run the test-suite on any other rt-kernel target with enough memory. One of the emulated boards for instance is pretty convenient:
```
$ cmake --build build.integrator/ --target pf_test
[  2%] Built target gtest
[  5%] Built target osal
[ 43%] Built target profinet
[ 45%] Built target gmock
[100%] Built target pf_test
$ /opt/rt-tools/qemu/bin/qemu-system-arm -M integratorcp -nographic -semihosting -kernel build.integrator/pf_test.elf --append "--gtest_filter=AlarmUnitTest*"
netif down
netif up (192.168.0.2)
link up
Note: Google Test filter = AlarmUnitTest*
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from AlarmUnitTest
[ RUN      ] AlarmUnitTest.AlarmCheckAddDiagItemToSummary
[       OK ] AlarmUnitTest.AlarmCheckAddDiagItemToSummary (0 ms)
[ RUN      ] AlarmUnitTest.AlarmCheckQueueHandling
[       OK ] AlarmUnitTest.AlarmCheckQueueHandling (0 ms)
[----------] 2 tests from AlarmUnitTest (0 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (0 ms total)
[  PASSED  ] 2 tests.
QEMU: Terminated

```

**Pull request merged**
