### PR TITLE
Include MAC address in DCP get response

### PR DESCRIPTION
**Pull request by pyhys**
Found with Automated RT Tester

### CODE REVIEW

**Comment by JanVasina** [comment]
I have tested the proposed changes (adding the **request_is_identify** parameter to the `pf_dcp_get_req()` function and it solved the problem with responding the MAC address.

Just a note to the `pf_dcp_get_req` function: if the DCP req is unknown (this is a part of Automated RT Tester test cases), the function should response an error. Taken from Wireshark:

_Request from Automated RT Tester:_

```
PROFINET DCP, Get Req, Xid:0x9, Status from Reserved - Unknown, Status from Reserved - Unknown, Status from Reserved - Unknown, Status from Reserved - Unknown
    ServiceID: Get (3)
    ServiceType: Request (0)
    Xid: 0x00000009
    Reserved: 0
    DCPDataLength: 8
    Option: Reserved (0)
    Suboption: Unknown (0)
    Option: Reserved (0)
    Suboption: Unknown (1)
    Option: Reserved (0)
    Suboption: Unknown (2)
    Option: Reserved (0)
    Suboption: Unknown (3)

```
_Actual incorrect response:_

```
PROFINET DCP, Get Ok , Xid:0x9, Reserved, Reserved, Reserved, Reserved, Reserved
    ServiceID: Get (3)
    ServiceType: Response Success (1)
    Xid: 0x00000009
    Reserved: 0
    DCPDataLength: 32
    Block: Reserved
    Padding: 1 byte
    Block: Reserved
    Padding: 1 byte
    Block: Reserved
    Padding: 1 byte
    Block: 
    Padding: 1 byte
    Block: Reserved
    Padding: 1 byte
    Block: 
    Block: Reserved
    Padding: 1 byte
    Block: 
    Padding: 1 byte
    Block: 
    parse error
        [Expert Info (Error/Protocol): parse error]
            [parse error]
            [Severity level: Error]
            [Group: Protocol]

```
_Correct response should be:_

```
PROFINET DCP, Get Ok , Xid:0x9, Response(Option unsupp.), Response(Option unsupp.), Response(Option unsupp.), Response(Option unsupp.)
    ServiceID: Get (3)
    ServiceType: Response Success (1)
    Xid: 0x00000009
    Reserved: 0
    DCPDataLength: 32
    Block: Control/Response, Status from Reserved - Unknown, BlockError: Option unsupp.
        Option: Control (5)
        Suboption: Response (4)
        DCPBlockLength: 3
        Option: Reserved (0)
        Suboption: Unknown (0)
        BlockError: Option unsupp. (1)
    Padding: 1 byte
    Block: Control/Response, Status from Reserved - Unknown, BlockError: Option unsupp.
        Option: Control (5)
        Suboption: Response (4)
        DCPBlockLength: 3
        Option: Reserved (0)
        Suboption: Unknown (1)
        BlockError: Option unsupp. (1)
    Padding: 1 byte
    Block: Control/Response, Status from Reserved - Unknown, BlockError: Option unsupp.
        Option: Control (5)
        Suboption: Response (4)
        DCPBlockLength: 3
        Option: Reserved (0)
        Suboption: Unknown (2)
        BlockError: Option unsupp. (1)
    Padding: 1 byte
    Block: Control/Response, Status from Reserved - Unknown, BlockError: Option unsupp.
        Option: Control (5)
        Suboption: Response (4)
        DCPBlockLength: 3
        Option: Reserved (0)
        Suboption: Unknown (3)
        BlockError: Option unsupp. (1)
    Padding: 1 byte

```

To solve the problem, I have changed the response in the case of error (`ret != 0`) at the end of the `pf_dcp_get_req()` function (from line 387, file pf_dcp.c):

```
  if (ret == 0)
  {
    if (skip == false)
    {
      ret = pf_dcp_put_block(p_dst, p_dst_pos, dst_max, opt, sub, true, block_info, value_length, p_value);
    }
  }
  else
  {
    if (skip == false)
    {
      ret = pf_dcp_put_block(p_dst,
                             p_dst_pos,
                             dst_max,
                             PF_DCP_OPT_CONTROL,
                             PF_DCP_SUB_CONTROL_RESPONSE,
                             true,
                             ((uint16_t)(opt) << 8) | ((uint16_t)(sub)),
                             sizeof(block_error),
                             &block_error);
    }
  }

```

**Comment by pyhys** [comment]
Great, thanks for your help!
Which test case in ART tester is this, so I can rreproduce it?

**Comment by JanVasina** [comment]
Sorry for delay, yes, the tests are DCP_2 and DCP_3. I am using Automated RT tester 2.4.1.3.

Just FYI, I have made a fork of your code and created a new branch [automated-rt-tester-patch-1](https://github.com/JanVasina/p-net/tree/JanVasina-automated-rt-tester-patch-1), where I put all my changes. Maybe it would help you.

**Comment by pyhys** [comment]
See Issue #90

**Pull request merged**
