### PR TITLE
Add sample_app IO Device GSDML file

### PR DESCRIPTION
**Pull request by nakarlsson**
Simple sample IO Device GSDML file
Three plugable modules
8 Bit Inputs
8 Bit Ouputs
8 Bit Inputs/8 Bit Outputs

### CODE REVIEW

**Comment by svenhaitjema** [comment]
Dear nakarlsson,

Thank you for the GSDML file, I am currently checking it, but have some problems with my PLC firmware version & TIA versions... The GSDML did pass the TIA check in both v14 and v15. I will provide feedback as soon as possible!

Kind regards,

Sven-Erik

**Comment by svenhaitjema** [comment]
Dear Nakarlsson,

Unfortunately I seem to be unable to setup the device properly in TIA 14. I am able to load the gsdml file, the device is visible in 'Accessible devices'. But after adding the device to devices & networks and setting up the IO system TIA is giving me: Not reachable in the device status. The IP addresses match, but I noticed that TIA does reset the device MAC to 00-0..... in Online & Diagnostics 

What I changed in the main_linux.c file: 
- The IP adres of the raspberry pi

I also changed the hostname of the raspberry pi to: rt-labs-dev, but only after my initial attempts at connecting failed. 

I am aware that this level of bug reporting from me to you equals: It doesn't work. Which is not very helpful so I am working on gathering more details. 

Maybe there is some basic step that I missed, or a field that needs to be adjusted in main_linux.c that I missed. If that is the case, please let me know and I will retest. 

Kind regards,

Sven-Erik

**Comment by nakarlsson** [comment]
A wireshark of the DCP and Connect might help. I tested with the TwinCAT built-in RT-Profinet Controller and the IO tester

**Comment by svenhaitjema** [comment]
Dear Nakarlsson, 

I took my project to an experienced controls engineer who was able to help out a bit further. His first remark about the GSDML file after loading it in TIA was: It appeared odd to him that we were only allowed to mount one module in I, while there are 3 possible modules present: 
- 8 bits I
- 8 bits I 8 bits O
- 8 bits O

We dragged the 8 bits I 8 bits O into I. 

I enabled a lower debug level in: main_log.h by setting

#define MAIN_LOG_LEVEL          MAIN_LOG_LEVEL_ERROR
to 
#define MAIN_LOG_LEVEL          MAIN_LOG_LEVEL_DEBUG    

This yielded a couple of error outputs in the application, depending on which sub module was attached to I in TIA, the general error in TIA was: The connection to the IO device was aborted by the IO controller. So instead of sending a wireshark log, I will provide the application output, since it appears the problem is not in the DCP / Connect sequence (This error differed from my pc with VMWare setup, that could explain the difference). Please let me know if you still need a wireshark log. 

The application log was as following when going online with the PLC (a s7-1215 now) and the 8 bits I 8 bits O was dragged into I: 
[INFO ] APP: connect call-back 0 0 0 0
[DEBUG] APP: state call-back 1
[DEBUG] APP: New data status 0x25
[INFO ] APP: write call-back: idx 123
[INFO ] APP: write call-back: idx 124
[INFO ] APP: dcontrol call-back (cmd:1) 0 0 0 0 
[DEBUG] APP: state call-back 2
[ERROR] PPM(479): iocs_len is zero
[ERROR] PPM(479): iocs_len is zero
[ERROR] PPM(479): iocs_len is zero
[DEBUG] APP: state call-back 0
ABORT err_cls 253  err_code 5
[DEBUG] APP: Return from apprdy: -1
[DEBUG] APP: abort 

when taking the 8 BITS I or 8 BITS O module there was difference in the output:

[ERROR] CMDEV(1604): api 0 exp slot 1 subslot 1 and dir 1 not found
[INFO ] APP: connect call-back 0 0 0 0
[DEBUG] APP: state call-back 1
[DEBUG] APP: New data status 0x35
[INFO ] APP: dcontrol call-back (cmd:1) 0 0 0 0 
[DEBUG] APP: state call-back 2
[ERROR] PPM(479): iocs_len is zero
[ERROR] PPM(479): iocs_len is zero
[ERROR] PPM(479): iocs_len is zero
[ERROR] PPM(495): No data descriptor found for set iocs
[DEBUG] APP: state call-back 3
[DEBUG] APP: Return from apprdy: 0
[DEBUG] APP: state call-back 0
ABORT err_cls 253  err_code 5
[DEBUG] APP: abort 

Does this output help? 


Kind regards,

Sven-Erik

**Comment by nakarlsson** [comment]
Thanks for the info, yes I'd like an Wireshark as a complement if possible.

**Comment by svenhaitjema** [comment]
Dear Nakarlsson,

Hereby the wireshark log, my approach was as following:
- program the right code in the plc.
- Turn off the power.
- Boot the pn_dev application on the raspberry pi
- Start wireshark logger
- Turn on power to the PLC
- Keep logging till the raspberry pi throws the error.
- Stop log

Please let me know if you need a better log or anything else. Thank you so
much for your time.

Kind regards

**Comment by nakarlsson** [comment]
I only see the first DCP broadcast. You would need to use a tap or if you manage to run wireshark on the IODevice?

**Comment by svenhaitjema** [comment]
Dear Nakarlsson, 

Hereby a more extensive log (wireshark on the IODevice). Hope this helps!

Kind regards,

Sven-Erik Haitjema
[IODevice_log.zip](https://github.com/rtlabs-com/p-net/files/3755034/IODevice_log.zip)

**Comment by svenhaitjema** [comment]
Dear Nakarlsson,

Do you need any additional information/ Can I do more testing to help out? 


Kind regards,

Sven-Erik Haitjema

**Comment by nakarlsson** [comment]
Thanks for the log Sven-Erik, I'm looking into it.

**Comment by nibeh** [comment]
I'm able to confirm the errors, please see log attached.
[p-net-problem.zip](https://github.com/rtlabs-com/p-net/files/3890681/p-net-problem.zip)

Linux example app is not able to read some packets:
> ttrtrtrrrrrrrrtrrrrrtrrrrrrrrrttrrtttrrtrt[ERROR] CMRPC(2500): Unknown packet_type 1
> [ERROR] CMDEV(1604): api 0 exp slot 1 subslot 1 and dir 2 not found
> trtr[ERROR] PPM(479): iocs_len is zero
> [ERROR] PPM(479): iocs_len is zero
> [ERROR] PPM(479): iocs_len is zero
> [ERROR] PPM(479): iocs_len is zero
> trrABORT err_cls 253  err_code 18

I tested with TIA 15.1 and Siemens S7-1212C PLC.

**Comment by svenhaitjema** [comment]
Dear Nakarlsson, Could I provide you with more information to debug this issue? Or could you point me in a direction so I can go through the code myself?

**Comment by nakarlsson** [comment]
Sorry, been quite busy with other projects.  Could you perhaps provide a similar (connect sequence) wireshark/pcap for a IODevice that is successful? As a ref,  I don't have access to a S7 at the moment.

one thing, it would be interesting to know why the param.end frame #35 is considered Malformed in Wireshark.

**Comment by nibeh** [comment]
I just tried to rebuild your GSDML and configuration in our Profinet stack and was able to generate the following working capture.
[demo-working.zip](https://github.com/rtlabs-com/p-net/files/3920594/demo-working.zip)

**Comment by nakarlsson** [comment]
Can you share your changes? I'll test it with the TwinCAT profinet RT conroller and the Device IO tester

**Comment by nakarlsson** [comment]
@nibeh, could you post your version of the GSDML?

**Comment by svenhaitjema** [comment]
> I just tried to rebuild your GSDML and configuration in our Profinet stack and was able to generate the following working capture.
> [demo-working.zip](https://github.com/rtlabs-com/p-net/files/3920594/demo-working.zip)

@nibeh Could you clarify your message? Did you take the current repo GSDML file and adapt it to work for you own developed profinet stack?

**Comment by nakarlsson** [comment]
I hope to have a S7 inhouse soon, from the Wirsharks, there seems to be an issue with parameters.

**Comment by Svenson12** [comment]
I'm currently evaluating this stack for a project and I'm facung the same issue.
Is there any progress in solving it or a time frame?

**Comment by hefloryd** [comment]
A fix is in progress and should be posted shortly.

**Comment by hefloryd** [comment]
A fix was posted in PR #6 and was tested on an S7-1200, using this sample app.

**Pull request merged**
